services:
  backend:
    build: ./rentAuto-api
    ports:
      - "3000:3000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      DB_HOST: db.rhujlydpcdmxgsootmzi.supabase.co
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: Tonny@sey19
      DB_NAME: postgres

  frontend:
    build: ./rentAuto-web
    ports:
      - "80:80"
    depends_on:
      - backend