server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Це магічний рядок, який виправляє твою проблему:
        try_files $uri $uri/ /index.html;
    }
}